language: go

go:
  - 1.12.1
  - tip

# Skip the install step. Don't `go get` dependencies. Only build with the
# code in vendor/
install: true

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck 
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0

script:
  - go vet ./...
  - staticcheck ./...
  - golangci-lint run --disable=structcheck
  - go test -race ./...
  - golint -set_exit_status $(go list ./...) # exclude vendor directory

#after_script:
  
